//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUPUX.Forms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Primary</string>\r\n  <string>Secondary</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection UseCaseType {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["UseCaseType"]));
            }
            set {
                this["UseCaseType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Basic Flow</string>
  <string>Alternative Flow</string>
  <string>Exceptional Flow</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FlowType {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FlowType"]));
            }
            set {
                this["FlowType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>User</string>\r\n  <string>System</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection StepFlowType {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["StepFlowType"]));
            }
            set {
                this["StepFlowType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>High</string>\r\n  <string>Medium</string>\r\n  <string>Low</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection Dificulty {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Dificulty"]));
            }
            set {
                this["Dificulty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>High</string>\r\n  <string>Medium</string>\r\n  <string>Low</string>\r\n</ArrayO" +
            "fString>")]
        public global::System.Collections.Specialized.StringCollection Priority {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Priority"]));
            }
            set {
                this["Priority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Functional</string>\r\n  <string>Non Functional</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RequerimentType {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RequerimentType"]));
            }
            set {
                this["RequerimentType"] = value;
            }
        }
    }
}
